### PR TITLE
Update autoconf/automake files. Closes: #1458

### PR DESCRIPTION
**Pull request by radioactiveman**
Use the latest version from:
- https://git.savannah.gnu.org/gitweb/?p=config.git

### CODE REVIEW

**Comment by radioactiveman** [comment]
@jlindgren90: Where are `config.rpath` and `install-sh` hosted? I only found out that `config.rpath` is related to `gettext`. But the file is not found in its Git repo.

**Comment by jlindgren90** [comment]
I think that config.rpath comes from gettext and install-sh comes from libtool. It's been a long time since I did it and I'm not at a computer right now, but it looks like the gettextize and libtoolize commands will create/update the files if given the right options.

**Comment by jlindgren90** [comment]
I went ahead and updated the files with 5aa135a2471aaec8ab323c1dbda8ca1a65339b5b. Thanks!

**Comment by radioactiveman** [comment]
Thanks John, I have been busy with other things the last few days.

**Pull request closed without merging**
