### PR TITLE
Add support for signed 24 bit packed little endian (S24_3LE).

### PR DESCRIPTION
**Pull request by cdealti**

### CODE REVIEW

**Comment by jlindgren90** [comment]
This looks like a good start, but it will have to wait till after 3.8.

Some observations:
- FMT_S24_3LE/BE should be added to the end of the enum so as not to change the values of the names that come before.
- audio_interlace/deinterlace() will have to be updated.  Shouldn't be too difficult.
- All the macros in this file predate the switch to C++.  I'd like to convert them to templates before adding any more.
- With recent changes in 3.8, it should be possible to detect whether packed or unpacked output is needed automatically.  I would rather do that than requiring the user to figure it out.

**Comment by cdealti** [comment]
Thanks for reviewing this.
Do you have hints on audio_interlace/deinterlace() functions and how to test them for the packed formats?

**Comment by jlindgren90** [comment]
Should be working in master now.

**Pull request closed without merging**
