### PR TITLE
Adding stop after each song option

### PR DESCRIPTION
**Pull request by sanchezfauste**
Add the option to stop playback after each song.

I use audacious to play tracks in live shows. I need that after each song the playback stops and the position of the playlist is advanced. That is like a permanent "Stop after current song".

See: https://github.com/audacious-media-player/audacious-plugins/pull/61

### CODE REVIEW

**Comment by jlindgren90** [comment]
You can do this already with "No Playlist Advance", then manually hit "Next" before you start the next song.  I guess you want the "Next" step to happen automatically, but we can't add a new command/setting for every possible sequence of operations.  The UI would simply become unmanageable.

**Comment by sanchezfauste** [comment]
This is what I do actually, but would be great if "next" step is performed automatically. Is there any way to add this option without making the interface more complicated?

**Comment by jlindgren90** [comment]
You could bind a hotkey to "audtool --playlist-advance ; audtool --playback-play"

**Comment by sanchezfauste** [comment]
Thank you! I will test it.

**Pull request closed without merging**
