### PR TITLE
Allow to truncate formatted strings in playlist

### PR DESCRIPTION
**Pull request by iDarkTemplar**
This allows to truncate really long artist names with format like following:

${?artist:${artist#25} - }${title}

### CODE REVIEW

**Comment by iDarkTemplar** [comment]
Works with other string tags too. Doesn't work with integer tags, like years, and isn't intended to work with them.

**Comment by iDarkTemplar** [comment]
Not ready for merge. Found issue with non-ascii strings breaking. Need to find correct way to get non-ascii string length and truncate such strings.

**Comment by iDarkTemplar** [comment]
Issue with non-ascii strings with fixed, but tested only with UTF-8 system locale. Ready for review/merge again.

**Comment by jlindgren90** [comment]
Nice work, thanks!

I simplified the changes a bit making use of GLib's existing UTF-8 utilities, and merged this:
https://github.com/audacious-media-player/audacious/commit/38c27d3c28b722650980258faa13ccccc1b35a08

**Comment by iDarkTemplar** [comment]
Thank you!

**Pull request closed without merging**
