### PR TITLE
Add Uzbek translation

### PR DESCRIPTION
**Pull request by umidjonalmasov**

### CODE REVIEW

**Comment by jlindgren90** [comment]
Hi @umidjonalmasov, thanks very much for the contribution! We use Transifex to manage translations for Audacious (https://www.transifex.com/audacious/audacious/); would you kindly be willing to submit your updates there?

/cc @radioactiveman

**Comment by umidjonalmasov** [comment]
Ok. I've already uploaded the translation file in Transifex.

**Comment by jlindgren90** [comment]
Thanks very much. We'll pull your updates into the next release.

**Comment by umidjonalmasov** [comment]
What about Launchpad? Are translations from this platform used?

**Comment by jlindgren90** [comment]
We don't use Launchpad at all for Audacious.

**Comment by radioactiveman** [comment]
@jlindgren90: The translations on Transifex are not up-to-date for 4.2. Do you plan to release a 4.1.1 version? If not, I would update the files on Transifex.

**Comment by jlindgren90** [comment]
@radioactiveman Let's skip 4.1.1 and update Transifex to what's in master.  Thanks.  I have a little bit of time later today, I can run some checks and tag 4.2-beta1 if that works for you.

**Comment by umidjonalmasov** [comment]
Ok. Let's update to 4.2.

**Comment by radioactiveman** [comment]
@jlindgren90: Sounds great, thank you. :+1: I have just updated the files on Transifex.

**Comment by radioactiveman** [comment]
@umidjonalmasov: Please make sure to also translate [audacious-plugins](https://www.transifex.com/audacious/audacious/audacious-plugins/). If both files for Uzbek are at least 50% translated, I will add them for Audacious 4.2. Thanks for your contribution.

**Pull request closed without merging**
