### PR TITLE
audqt: Make file path in info window selectable. Closes: #1174

### PR DESCRIPTION
**Pull request by radioactiveman**
This is useful when you want to copy/paste only a part of
the file path (like the artist) to the song metadata entries.

### CODE REVIEW

**Comment by radioactiveman** [comment]
Unfortunately there is a regression: The album art can sometimes be cut-off. Looking for a fix.

**Comment by jlindgren90** [comment]
I wish I could remember what that "lack of proper wrapping" comment referred to. Is there any noticeable difference in text wrapping with this change?

**Comment by jlindgren90** [comment]
I believe this was the text wrapping issue:

Before:
image

After:
image

**Comment by radioactiveman** [comment]
It looks like Qt only breaks on spaces, dashes and slashes.
Do you think a path can get that long in practice without any of these characters?

I would suggest to limit the width, resolving also the mentioned difference when there is no album art.
Your example is then cut-off, but the user still can copy the whole path via the context menu.

```c++
m_uri_label.setFixedWidth(2 * sizes.OneInch);
```

**Comment by jlindgren90** [comment]
@radioactiveman I think `QTextEdit` can do everything we want here (selection and wrapping). Please try ddcbce7f9f4b219bb09d2c2be37363d526c0de1b.

**Comment by radioactiveman** [comment]
Nice find, that works fine as well. Only the "no album art" case looks a bit compressed now.

Original:


https://github.com/audacious-media-player/audacious/commit/ddcbce7f9f4b219bb09d2c2be37363d526c0de1b:


Suggestion:
Enable "stretch" for the label, see diff below.
For some reason `Qt:AlignBottom` has no effect. Then it would look like before.






```diff
diff --git a/src/libaudqt/infowin-qt.cc b/src/libaudqt/infowin-qt.cc
index 26c4ccbaa..98ffe2f00 100644
--- a/src/libaudqt/infowin-qt.cc
+++ b/src/libaudqt/infowin-qt.cc
@@ -18,13 +18,8 @@
  * the use of this software.
  */
 
-#include <math.h>
-
 #include <QDialog>
 #include <QDialogButtonBox>
-#include <QEvent>
-#include <QHBoxLayout>
-#include <QImage>
 #include <QLabel>
 #include <QPointer>
 #include <QPushButton>
@@ -69,17 +64,14 @@ InfoWindow::InfoWindow(QWidget * parent) : QDialog(parent)
     setWindowTitle(_("Song Info"));
     setContentsMargins(margins.TwoPt);
 
-    m_image.setAlignment(Qt::AlignCenter);
     m_uri_label.setFixedWidth(2 * audqt::sizes.OneInch);
     m_uri_label.setFrameStyle(QFrame::NoFrame);
     m_uri_label.setReadOnly(true);
     m_uri_label.viewport()->setAutoFillBackground(false);
 
     auto left_vbox = make_vbox(nullptr);
-    left_vbox->addWidget(&m_image);
-    left_vbox->addWidget(&m_uri_label);
-    left_vbox->setStretch(0, 1);
-    left_vbox->setStretch(1, 0);
+    left_vbox->insertWidget(0, &m_image, 1, Qt::AlignCenter);
+    left_vbox->insertWidget(1, &m_uri_label, 1); // Qt:AlignBottom has no effect here
 
     auto hbox = make_hbox(nullptr);
     hbox->addLayout(left_vbox);
```

**Comment by jlindgren90** [comment]
Applied with 70223153f0dcbde486971485e8a89b9598a90ba1, thanks :+1:

**Pull request closed without merging**
