### PR TITLE
audqt: Implement the 'Jump to Song' Dialog.

### PR DESCRIPTION
**Pull request by stevestorey**
Hi Audacious developers. I found https://redmine.audacious-media-player.org/issues/978 and have made an attempt to add the missing feature. I'm not normally a C++ developer, so please do let me know if I've done anything silly or unwise.

### CODE REVIEW

**Comment by kaniini** [comment]
Looks OK to me.

**Comment by radioactiveman** [comment]
@stevestorey: Thanks for your contribution. :+1: I have pushed minor fixes via commit ba4a4dd5d3783e3b69c7fe6419f3aae2a1f410d9.

Further comments:
- Is it possible to use an entry instead of combobox for the filter entry? Clicking on the combobox arrow has no effect and feels wrong. A QLineEdit would also support `setClearButtonEnabled(true)`.
- The queue button label should be changed to "Unqueue" if the track gets queued or is already queued initially. If that's too complicated, use a general text like "Queue/Unqueue".

Could you please check this? Thank you.

**Comment by stevestorey** [comment]
@radioactiveman thanks for the feedback and the improvements commit. I hope I've addressed both points in https://github.com/audacious-media-player/audacious/pull/43

Also, while I'm here - something I wondered about - what's the difference between `_('xx')`, `_N('xx')` and `translate_str(_N('xx'))`

**Comment by radioactiveman** [comment]
Thanks @stevestorey for your fast response and fixes. Regarding your question:

- `N_(str)` only marks _str_ as translatable
- _(str) in addition calls gettext (i18n library) to get the translation for _str_
- `translate_str(str)` in addition replaces underscores with ampersands (GTK uses underscores, Qt ampersands for accelerators)

**Pull request merged**
